export EVENT_HUB_CONNECTION_STR=<conn-str>
export EVENTHUB="arpita_loadtest1"
export DURATION=60
export PAYLOAD=512
export BATCH=1000
export PAYLOAD_JSON_SIZE=256KB

export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0

docker build -t azure_send .
docker rm -f azure_send || true
docker run -e DURATION=$DURATION -e PAYLOAD=$PAYLOAD -e BATCH=$BATCH -e EVENTHUB=$EVENTHUB -e EVENT_HUB_CONNECTION_STR=$EVENT_HUB_CONNECTION_STR, -e ADDRESS=$ADDRESS -e SAS_POLICY=$SAS_KEY -e SAS_KEY=$SAS_KEY -e PAYLOAD_JSON_SIZE=$PAYLOAD_JSON_SIZE --name azure_send azure_send
